"""Change model_name to openai_model_name.

Revision ID: 04eb6151bdd1
Revises: a0298a3ad45b
Create Date: 2024-09-18 15:50:18.179479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04eb6151bdd1'
down_revision: Union[str, None] = 'a0298a3ad45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawleropenairecord', sa.Column('openai_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('crawleropenairecord', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawleropenairecord', sa.Column('model_name', sa.VARCHAR(), nullable=False))
    op.drop_column('crawleropenairecord', 'openai_model_name')
    # ### end Alembic commands ###
