"""Adding additional data models for the aggregations.

Revision ID: 8ea2d3372010
Revises: 97b4687bc90e
Create Date: 2024-10-22 13:17:44.957319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ea2d3372010'
down_revision: Union[str, None] = '97b4687bc90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childcareopenairecord',
    sa.Column('webpage_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provides_before_care', sa.Boolean(), nullable=True),
    sa.Column('before_care_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_care_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_care_quote_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provides_after_care', sa.Boolean(), nullable=True),
    sa.Column('after_care_end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_care_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_care_quote_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('openai_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combinedchildcareopenairecord',
    sa.Column('provides_before_care', sa.Boolean(), nullable=True),
    sa.Column('before_care_start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_care_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provides_after_care', sa.Boolean(), nullable=True),
    sa.Column('after_care_end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_care_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_care_citations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_care_citation_snippets', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_care_citations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_care_citation_snippets', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('openai_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('evals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('school_id', sa.INTEGER(), nullable=True),
    sa.Column('page_url', sa.VARCHAR(), nullable=True),
    sa.Column('true_label', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('combinedchildcareopenairecord')
    op.drop_table('childcareopenairecord')
    # ### end Alembic commands ###
