"""Modifying the openai childcare extraction models.

Revision ID: b7e1394dd00e
Revises: 8ea2d3372010
Create Date: 2024-10-22 14:15:30.549554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7e1394dd00e'
down_revision: Union[str, None] = '8ea2d3372010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('childcareopenairecord', sa.Column('before_care_quote_snippet_verified', sa.Boolean(), nullable=True))
    op.add_column('childcareopenairecord', sa.Column('after_care_quote_snippet_verified', sa.Boolean(), nullable=True))
    op.drop_column('childcareopenairecord', 'school_type')
    op.drop_column('combinedchildcareopenairecord', 'school_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combinedchildcareopenairecord', sa.Column('school_type', sa.VARCHAR(), nullable=False))
    op.add_column('childcareopenairecord', sa.Column('school_type', sa.VARCHAR(), nullable=False))
    op.drop_column('childcareopenairecord', 'after_care_quote_snippet_verified')
    op.drop_column('childcareopenairecord', 'before_care_quote_snippet_verified')
    # ### end Alembic commands ###
