"""init

Revision ID: e0a42e08fd1a
Revises: 21ba01dad18c
Create Date: 2024-10-09 10:27:49.293661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0a42e08fd1a'
down_revision: Union[str, None] = '21ba01dad18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawleropenairecord', sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawleropenairecord', 'prompt_version')
    # ### end Alembic commands ###
