"""Removed redundant is_before_or_after_care field.

Revision ID: e72717a27bfc
Revises: c275995b7eb5
Create Date: 2024-09-23 08:49:20.675837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e72717a27bfc'
down_revision: Union[str, None] = 'c275995b7eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
